#! /usr/bin/env php

<?php

use CJ\NewCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

require 'vendor/autoload.php';

$app = new Application('Laracast Demo','1.0');

$app->add(new NewCommand(new GuzzleHttp\Client));

$app->run();